spring:
  application:
    name: stats-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000
  config:
    import: "configserver:"

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    hostname: localhost
    prefer-ip-address: true
