server:
  port: 0
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
