server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/categories/**, /admin/categories/**, /admin/compilations/**, /admin/events/**, /users/**, /events/**, /compilations/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit/**, /stats/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
