spring:
  application:
    name: event-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  config:
    import: "configserver:"

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    prefer-ip-address: true
    hostname: localhost
