spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/postgres
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always

kafka:
  bootstrap-address: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:9092}
  topics:
    user-action: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

grpc:
  server:
    port: 0
    security:
      enabled: false
